# Generated by Django 4.2.7 on 2024-01-17 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_app', '0002_car_date_posted_car_location_car_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cv', models.ImageField(upload_to='cv')),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.car')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
