# Generated by Django 4.2.7 on 2024-01-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_job_seeker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price',
            new_name='sarlry',
        ),
        migrations.AlterField(
            model_name='job_seeker',
            name='Cv',
            field=models.ImageField(blank=True, null=True, upload_to='cv'),
        ),
    ]
