# Generated by Django 4.2.7 on 2024-01-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_rename_price_car_sarlry_alter_job_seeker_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='sarlry',
            new_name='salary',
        ),
    ]
